/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 steel_flower.gltf 
Author: gecko0307 (https://sketchfab.com/gecko0307)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/steel-flower-cade63ac08774fe3b71b6449ba3ac8a1
Title: Steel & Flower
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function SteelFlower(props) {
  const { nodes, materials } = useGLTF('/3d/steel_flower/steel_flower.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0, 0.045]} rotation={[-Math.PI, 0.56, -Math.PI]}>
          <group position={[-0.372, 0.791, -0.005]} rotation={[Math.PI / 2, -1.351, Math.PI / 2]}>
            <group position={[-0.008, 0.906, -0.008]} rotation={[-0.591, 0, 0]}>
              <mesh geometry={nodes.objFinger4_0.geometry} material={materials.mDarkMetal} />
              <mesh geometry={nodes.objFinger4_1.geometry} material={materials.mMetal} />
              <mesh geometry={nodes.objFinger4_2.geometry} material={materials.mDarkResin} />
            </group>
            <mesh geometry={nodes.objFinger2_0.geometry} material={materials.mDarkMetal} />
            <mesh geometry={nodes.objFinger2_1.geometry} material={materials.mMetal} />
          </group>
          <group position={[0.396, 0.791, -0.005]} rotation={[Math.PI / 2, 1.354, -Math.PI / 2]}>
            <group position={[-0.004, 0.901, -0.005]} rotation={[-0.606, 0, 0]}>
              <mesh geometry={nodes.objFinger3_0.geometry} material={materials.mDarkMetal} />
              <mesh geometry={nodes.objFinger3_1.geometry} material={materials.mMetal} />
              <mesh geometry={nodes.objFinger3_2.geometry} material={materials.mDarkResin} />
            </group>
            <mesh geometry={nodes.objFinger1_0.geometry} material={materials.mDarkMetal} />
            <mesh geometry={nodes.objFinger1_1.geometry} material={materials.mMetal} />
          </group>
          <mesh geometry={nodes.objHand1_0.geometry} material={materials.mMetal} />
        </group>
        <group position={[0, 2.644, 0]} rotation={[0.206, -0.636, 0.377]}>
          <group position={[0, 0, 0.947]} rotation={[0, 0, 0.167]} scale={0.411}>
            <group position={[-0.089, -0.134, -0.032]} rotation={[-0.28, -0.404, -2.571]}>
              <mesh geometry={nodes.Cylinder003_0.geometry} material={materials.mStebel2} />
              <mesh geometry={nodes.Cylinder003_1.geometry} material={materials.mTop} />
            </group>
            <group position={[0.018, -0.105, 0.007]} rotation={[-0.28, -0.404, 0.87]}>
              <mesh geometry={nodes.Cylinder002_0.geometry} material={materials.mStebel2} />
              <mesh geometry={nodes.Cylinder002_1.geometry} material={materials.mTop} />
            </group>
            <group position={[-0.04, -0.187, 0.01]} rotation={[-0.28, -0.404, -1.229]}>
              <mesh geometry={nodes.Cylinder001_0.geometry} material={materials.mStebel2} />
              <mesh geometry={nodes.Cylinder001_1.geometry} material={materials.mTop} />
            </group>
            <mesh
              geometry={nodes.Plane004_0.geometry}
              material={materials.mLilly}
              position={[0.078, 0.026, -0.069]}
              rotation={[0.276, -0.327, -3.027]}
              scale={0.801}
            />
            <mesh
              geometry={nodes.Plane002_0.geometry}
              material={materials.mLilly}
              position={[0.118, -0.123, 0.043]}
              rotation={[-0.087, -0.266, -2.122]}
              scale={0.883}
            />
            <mesh
              geometry={nodes.Plane003_0.geometry}
              material={materials.mLilly}
              rotation={[-0.021, -0.019, -0.84]}
            />
            <mesh geometry={nodes.Plane_0.geometry} material={materials.mLilly} scale={0.883} />
            <mesh
              geometry={nodes.Plane005_0.geometry}
              material={materials.mLilly}
              position={[-0.052, -0.104, -0.016]}
              rotation={[0.12, -0.06, 1.112]}
              scale={0.891}
            />
            <mesh
              geometry={nodes.Plane001_0.geometry}
              material={materials.mLilly}
              position={[0, 0, -0.162]}
              rotation={[-0.157, -0.136, 2.057]}
              scale={0.883}
            />
          </group>
          <mesh
            geometry={nodes.Cylinder_0.geometry}
            material={materials.mStebel}
            position={[-0.022, -0.177, 0.001]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3d/steel_flower/steel_flower.gltf')
