/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 sort-flower.gltf 
Author: jwilson32 (https://sketchfab.com/jwilson32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sort-of-flower-333aed4b4a4f4c5e931d6b84ac475761
Title: Sort Of Flower
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function SortOfFlower(props) {
  const { nodes, materials } = useGLTF('/3d/sort_of_flower/sort-flower.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={1}>
        <mesh
          geometry={nodes.pPlane1_lambert1_0.geometry}
          material={materials.lambert1}
          position={[1.375, 0.484, -1.499]}
          rotation={[0.206, 0.063, 0.2]}
        />
        <mesh
          geometry={nodes.pPlane2_lambert1_0.geometry}
          material={materials.lambert1}
          position={[1.294, 0.325, 1.65]}
          rotation={[2.048, -1.364, 2.178]}
        />
        <mesh
          geometry={nodes.pPlane3_lambert1_0.geometry}
          material={materials.lambert1}
          position={[-1.813, 0.26, 1.111]}
          rotation={[3.042, 0.232, -2.961]}
        />
        <mesh
          geometry={nodes.pPlane4_lambert1_0.geometry}
          material={materials.lambert1}
          position={[-1.183, 0.457, -1.662]}
          rotation={[0.481, 1.351, -0.212]}
        />
        <mesh
          geometry={nodes.pPlane9_lambert1_0.geometry}
          material={materials.lambert1}
          position={[-0.147, -0.085, 0.176]}
          rotation={[0, -0.798, 0]}
          scale={0.901}
        />
        <mesh
          geometry={nodes.pPlane10_lambert1_0.geometry}
          material={materials.lambert1}
          position={[-0.118, 0.466, 0.15]}
          rotation={[0, -0.665, 0]}
          scale={0.901}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/3d/sort_of_flower/sort-flower.gltf')
